name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout telegram-bot-api
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          fetch-depth: 0
          submodules: true
      
      - name: Environment
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gperf -y
          sudo apt install openssl libssl-dev -y
      
      - name: Build
        run: |
          cd telegram-bot-api
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api_linux_x86-64
          path: telegram-bot-api/build/telegram-bot-api

  build_darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout telegram-bot-api
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          fetch-depth: 0
          submodules: true
      
      - name: Environment
        run: |
          brew install gperf cmake openssl
      
      - name: Build
        run: |
          cd telegram-bot-api
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl/ -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build . --target install
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api_darwin_x86-64
          path: telegram-bot-api/build/telegram-bot-api

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout telegram-bot-api
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          fetch-depth: 0
          submodules: true
      
      - name: Environment
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
          Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue

      - name: Build
        run: |
          cd telegram-bot-api
          mkdir build
          cd build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api_win_x86-64
          path: telegram-bot-api/build/telegram-bot-api*